name: Deploy to Firebase Hosting on PR

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2
        
      - name: Setup de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          
      - name: Instalar dependencias
        run: npm install
        
      - name: Construir la aplicación
        run: npm run build
        
      - name: Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DULCECONMARIA_1CC5B }}
          projectId: dulceconmaria-1cc5b
