name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Renderctl
        run: |
          curl -o renderctl https://render.com/static/renderctl-latest-linux-amd64
          chmod +x renderctl
          sudo mv renderctl /usr/local/bin/

      - name: Start server on Render
        run: |
          renderctl service update srv-cnbjiq8l6cac73egku00 --start
