name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Renderctl
        run: |
          curl -o renderctl https://render.com/static/renderctl-latest-linux-amd64
          ls -lh renderctl
          chmod +x renderctl
          sudo mv renderctl /usr/local/bin/ || echo "Failed to move renderctl to /usr/local/bin/"

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Deploy to Render
        run: |
          renderctl service update srv-cnbjiq8l6cac73egku00 --start || echo "Failed to start server on Render"
